
services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    networks:
      - app-network

  ride-service:
    build: ./ride-service
    ports:
      - "3002:3002"
    networks:
      - app-network

  payment-service:
    build: ./payment-service
    ports:
      - "3001:3001"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - ride-service
      - payment-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
